-- =====================================================================
-- 06_migracion_productos.sql  ·  generado desde INVENTARIO_NIVELER.xlsx
-- =====================================================================
-- Los 80 productos del Excel, con su codigo, nombre e imagen. El Excel no
-- traia precios ni stock minimo: quedan en 0 y se completan desde la app
-- (Productos > Editar) o con un update masivo cuando esten definidos.
--
-- Es idempotente: se puede volver a ejecutar sin duplicar nada.
-- Ejecutar despues de 05_seed.sql.
-- =====================================================================

insert into productos (sku, nombre, imagen_url, stock_minimo, activo) values
  ('PRD-001', 'PORTAJABÓN MULTIFUNCIONAL', 'PRD-001.jpg', 0, true),
  ('PRD-002', 'DEPILADOR FACIAL FLAWLESS', 'PRD-002.png', 0, true),
  ('PRD-003', 'SET DE FOCOS PARA TOCADOR 10 EN 1', 'PRD-003.png', 0, true),
  ('PRD-004', 'LIBRO MÁGICO MI LIBRO EN ESPAÑOL', 'PRD-004.png', 0, true),
  ('PRD-005', 'MASAJEADOR FACIAL FOREVER', 'PRD-005.png', 0, true),
  ('PRD-006', 'VAPORIZADOR FACIAL PORTÁTIL', 'PRD-006.png', 0, true),
  ('PRD-007', 'ASPIRADORA ULTRAVIOLETA PRO', 'PRD-007.png', 0, true),
  ('PRD-008', 'PROYECTOR DE DIBUJO DINOSAURIO', 'PRD-008.png', 0, true),
  ('PRD-009', 'SECADOR 3 CABEZALES EN 1', 'PRD-009.jpg', 0, true),
  ('PRD-010', 'LLAVERO LINTERNA RECARGABLE', 'PRD-010.jpg', 0, true),
  ('PRD-011', 'SECADOR DE ZAPATOS ULTRAVIOLETA 2 BRAZOS', 'PRD-011.png', 0, true),
  ('PRD-012', 'CEPILLO DE LIMPIEZA 7 EN 1', 'PRD-012.png', 0, true),
  ('PRD-013', 'LAVADORA PERSONAL INTELIGENTE', 'PRD-013.jpg', 0, true),
  ('PRD-014', 'JUEGO PIPOCAS EN ACCIÓN', 'PRD-014.jpg', 0, true),
  ('PRD-015', 'CINTA MÁGICA FLAXE TAPE', 'PRD-015.jpg', 0, true),
  ('PRD-016', 'MOCHILA DE AHORRO PARA NIÑOS', 'PRD-016.jpg', 0, true),
  ('PRD-017', 'PARLANTE CHELERO PORTÁTIL', 'PRD-017.jpg', 0, true),
  ('PRD-018', 'BLOQUE MAGNÉTICO - 194 PCS', 'PRD-018.jpg', 0, true),
  ('PRD-019', 'CASTILLO PARK', 'PRD-019.jpg', 0, true),
  ('PRD-020', 'BLOQUE MAGNÉTICO - 81 PCS', 'PRD-020.png', 0, true),
  ('PRD-021', 'TRICICLO 3 EN 1 PARA BEBÉS', 'PRD-021.png', 0, true),
  ('PRD-022', 'ESTUCHE DE MAQUILLAJE EXPANDIBLE', 'PRD-022.png', 0, true),
  ('PRD-023', 'CEPILLO SECADOR 2 EN 1 DORADO Y VERDE', 'PRD-023.png', 0, true),
  ('PRD-024', 'MINIPLANCHA DE ROPA PORTÁTIL', 'PRD-024.png', 0, true),
  ('PRD-025', 'PIEDRA VOLCÁNICA PARA PIEL GRASA', 'PRD-025.png', 0, true),
  ('PRD-026', 'JOYERO DESMONTABLE', 'PRD-026.png', 0, true),
  ('PRD-027', 'MÁQUINA DE EXFOLIACIÓN RECARGABLE CELESTE', 'PRD-027.png', 0, true),
  ('PRD-028', 'AGENDA DE AHORROS', 'PRD-028.png', 0, true),
  ('PRD-029', 'SET DE CUCHILLOS 5 EN 1', 'PRD-029.png', 0, true),
  ('PRD-030', 'PIEDRA DEPILADORA', 'PRD-030.png', 0, true),
  ('PRD-031', 'PORTACUBO DE HIELO 3 EN 1', 'PRD-031.png', 0, true),
  ('PRD-032', 'MASAJEADOR DE PIES', 'PRD-032.png', 0, true),
  ('PRD-033', 'CEPILLO PLANCHA', 'PRD-033.png', 0, true),
  ('PRD-034', 'FOCO VENTILADOR A CONTROL REMOTO', 'PRD-034.jpg', 0, true),
  ('PRD-035', 'MINI PANEL LED PARA CELULAR', 'PRD-035.jpg', 0, true),
  ('PRD-036', 'CACTUS BAILARIN', 'PRD-036.jpg', 0, true),
  ('PRD-037', 'DUCHA PORTÁTIL RECARGABLE', 'PRD-037.jpg', 0, true),
  ('PRD-038', 'PARLANTE G', 'PRD-038.png', 0, true),
  ('PRD-039', 'SECADOR DE ROPA PORTÁTIL', 'PRD-039.png', 0, true),
  ('PRD-040', 'BOLSAS AHORRA ESPACIO 8 EN 1', 'PRD-040.png', 0, true),
  ('PRD-041', 'LIMADOR DE UÑAS PARA BEBÉS', 'PRD-041.png', 0, true),
  ('PRD-042', 'AIRPOP MAGIC - Máquina de Pipocas sin Aceite', 'PRD-042.png', 0, true),
  ('PRD-043', 'SET 7 EN 1 DE ENVASES PARA CEREALES', 'PRD-043.png', 0, true),
  ('PRD-044', 'CINTURÓN DE CÓLICOS', 'PRD-044.png', 0, true),
  ('PRD-045', 'MALLA PARA VENTANAS MAGNÉTICA', 'PRD-045.png', 0, true),
  ('PRD-046', 'SOMBRILLA PARA PARABRISAS', 'PRD-046.png', 0, true),
  ('PRD-047', 'ROMANILLA DIGITAL', 'PRD-047.png', 0, true),
  ('PRD-048', 'SMARTPACK ORGANIZADORES DE VIAJE', 'PRD-048.jpg', 0, true),
  ('PRD-049', 'COLÁGENO RENOVA', 'PRD-049.png', 0, true),
  ('PRD-050', 'GIMNASIO Y ANDADOR 2 EN 1 PARA BEBÉ', 'PRD-050.jpg', 0, true),
  ('PRD-051', 'GATITO A CONTROL REMOTO', 'PRD-051.jpg', 0, true),
  ('PRD-052', 'PISTOLA LANZA BURBUJAS', 'PRD-052.png', 0, true),
  ('PRD-053', 'PERRO ROBOT A CONTROL BLANCO', 'PRD-053.jpg', 0, true),
  ('PRD-054', 'BLOQUES MAGNETICOS 209 PCS (SIN LUCES)', 'PRD-054.jpg', 0, true),
  ('PRD-055', 'BLOQUES MAGNETICOS 68PCS (SIN LUCES)', 'PRD-055.jpg', 0, true),
  ('PRD-056', 'BASTA ELECTRÓNICO', 'PRD-056.png', 0, true),
  ('PRD-057', 'BOLSAS AHORRA ESPACIO 5 EN 1', 'PRD-057.png', 0, true),
  ('PRD-058', 'KIT DE VINO Y BILLETERA DE REGALO', 'PRD-058.jpg', 0, true),
  ('PRD-059', 'BOLSO MAGNÉTICO', 'PRD-059.png', 0, true),
  ('PRD-060', 'MAQUINA SACA PICADOS', 'PRD-060.png', 0, true),
  ('PRD-061', 'LINTERNA DE CABEZA 2 LED', 'PRD-061.jpg', 0, true),
  ('PRD-062', 'LINTERNA DE CABEZA 3 LED', 'PRD-062.png', 0, true),
  ('PRD-063', 'CUELLERA MASAJEADOR DE VIAJE', 'PRD-063.png', 0, true),
  ('PRD-064', 'MINI MALETA DE MAQUILLAJE', 'PRD-064.png', 0, true),
  ('PRD-065', 'DESINFECTANTE SECA ZAPATOS 4 BRAZOS EN 1', 'PRD-065.png', 0, true),
  ('PRD-066', 'SET DE VAJILLA DE SILICONA PARA BEBÉ', 'PRD-066.png', 0, true),
  ('PRD-067', 'MINI LAVADORA DE ROPA INTERIOR', 'PRD-067.jpg', 0, true),
  ('PRD-068', 'MINI EXTRACTOR DE NARANJA', 'PRD-068.jpg', 0, true),
  ('PRD-069', 'LINTERNA DE CABEZA 1 LED', 'PRD-069.jpg', 0, true),
  ('PRD-070', 'EXTRACTOR DE PUNTOS NEGROS Y ESPINILLAS A VAPOR', 'PRD-070.jpg', 0, true),
  ('PRD-071', 'MASAJEADOR 4 BRAZOS PARA CUELLO', 'PRD-071.jpg', 0, true),
  ('PRD-072', 'MÁQUINA DE RADIO FRECUENCIA CON OZONO FACIAL', 'PRD-072.png', 0, true),
  ('PRD-073', 'PARLANTE ALAXE', 'PRD-073.jpg', 0, true),
  ('PRD-074', 'PEINE MASAJEADOR VIBRATORIO PORTÁTIL', 'PRD-074.jpg', 0, true),
  ('PRD-075', 'MINI PISTOLA MASAJEADORA FISIOTERAPIA', 'PRD-075.jpg', 0, true),
  ('PRD-076', 'PACK 2X1 PARCHES BAJA FIEBRE Y DOLOR DE CABEZA PARA BEBÉ (PAGA 6 U Y RECIBE 12 U)', 'PRD-076.png', 0, true),
  ('PRD-077', 'LIMPIADOR FACIAL FOREVER', null, 0, true),
  ('PRD-078', 'DEPILADORA LÁSER IPL 999.990 DISPAROS', 'PRD-078.png', 0, true),
  ('PRD-079', 'ESTANTE VERDURERO DE 5 NIVELES', null, 0, true),
  ('PRD-080', 'ASISTENTE AMAZON ALEXA', null, 0, true)
on conflict (sku) do update set
  nombre     = excluded.nombre,
  imagen_url = excluded.imagen_url,
  activo     = excluded.activo,
  updated_at = now();

-- Verificacion rapida
-- select count(*) as productos, count(imagen_url) as con_imagen from productos;
